apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance-configuration
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/laurobmb/ocp4-compliance-operator'
    targetRevision: HEAD
    path: compliance-policys/compliance_yamls/configurations
  destination:
    name: in-cluster
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
