---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: compliance
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: malima
        url: https://api.malima.rhbr-lab.com:6443
  template:
    metadata:
      name: '{{cluster}}-compliance'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
          - Delete=confirm
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - Replace=true
      source:
        repoURL: https://github.com/laurobmb/ocp4-compliance-operator
        targetRevision: main
        path: compliance-policys/compliance_yamls
      destination:
        namespace: openshift-compliance
        server: '{{url}}'