apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/laurobmb/ocp4-compliance-operator'
    targetRevision: HEAD
    path: compliance-policys/compliance_yamls/install_operator
  destination:
    server: 'https://api.malima.rhbr-lab.com:6443'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
